spring:
  application:
    name: realtime-polls
  datasource:
    url: jdbc:postgresql://localhost:5432/polldb
    username: postgres
    password: pass
    hikari:
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    user: postgres
    password: pass
pg-listener:
  wait-ms: 500
